# Generated by Django 5.2 on 2025-04-17 08:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
            ],
        ),
        migrations.AlterField(
            model_name='pipe',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=2056),
        ),
    ]
