# Generated by Django 5.2 on 2025-04-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_valve_alter_pipe_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valve',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
